SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR aarch64)

IF (DEFINED ENV{LLVM_PATH})
    SET(LLVM_PATH "$ENV{LLVM_PATH}")
ELSE()
    MESSAGE(FATAL_ERROR "Missing environment variable LLVM_PATH.")
ENDIF()

IF (DEFINED ENV{RPI_SYSROOT})
    SET(RPI_SYSROOT "$ENV{RPI_SYSROOT}")
ELSE()
    MESSAGE(FATAL_ERROR "Missing environment variable RPI_SYSROOT.")
ENDIF()

SET(_triple aarch64-none-linux-gnu)

SET(CMAKE_CROSSCOMPILING TRUE)
SET(CMAKE_SYSROOT "${RPI_SYSROOT}")

SET(CMAKE_C_COMPILER ${LLVM_PATH}/bin/clang)
SET(CMAKE_CXX_COMPILER ${LLVM_PATH}/bin/clang++)
SET(CMAKE_AR ${LLVM_PATH}/bin/llvm-ar)

SET(CMAKE_C_COMPILER_TARGET ${_triple})
SET(CMAKE_CXX_COMPILER_TARGET ${_triple})
SET(CMAKE_ASM_COMPILER_TARGET ${_triple})

SET(CMAKE_SHARED_LINKER_FLAGS
     -fuse-ld=lld
)

SET(CMAKE_EXE_LINKER_FLAGS
     -fuse-ld=lld
)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
