#pragma once

/*
 * Copyright (C) 2019 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <stdbool.h>
#include <stdint.h>
#include <sys/types.h>

extern "C" {

struct AdbdWifiCallbacksV1 {
    // Enables discovery. |ourSPAKE2Key| is the SPAKE2Key generated by system
    // server, |sz| is the size of |ourSPAKE2Key|.
    bool (*enable_discovery)(const uint8_t* ourSPAKE2Key, uint64_t sz);
    // Disables discovery.
    void (*disable_discovery)(void);
    // During the pairing process, once the client's public key is stored,
    // it will send it's own pairing request to send to the client to exchange
    // its public key. If |sz| is zero, this means the pairing failed and adbd
    // should abort the connection.
    void (*send_pairing_request)(const uint8_t* pairing_request, uint64_t sz);
    // Notify that the framework was disconnected.
    void (*on_framework_disconnected)(void);
    // Notify that the framework was connected.
    void (*on_framework_connected)(void);
};

struct AdbdWifiCallbacks {
    uint32_t version;
    union {
        AdbdWifiCallbacksV1 v1;
    } callbacks;
};

struct AdbdWifiContext;

AdbdWifiContext* adbd_wifi_new(AdbdWifiCallbacks* callbacks);
void adbd_wifi_delete(AdbdWifiContext* ctx);
void adbd_wifi_run(AdbdWifiContext* ctx);

// Iterate through the list of authorized public keys.
// Return false from the callback to stop iteration.
void adbd_wifi_get_public_keys(AdbdWifiContext* ctx,
                               bool (*callback)(const char* public_key, size_t len, void* arg),
                               void* arg);

// Let system_server know that a key has been successfully used for authentication.
uint64_t adbd_wifi_notify_auth(AdbdWifiContext* ctx, const char* public_key, size_t len);

// Let system_server know that a connection has been closed.
void adbd_wifi_notify_disconnect(AdbdWifiContext* ctx, uint64_t id);

// Let system_server know there is a pairing request. The request is queued and
// will be handled once it reaches the top of the queue.
void adbd_wifi_pairing_request(AdbdWifiContext* ctx,
                               const uint8_t* public_key,
                               uint64_t size_bytes);

enum AdbdWifiFeature {
};

bool adbd_wifi_supports_feature(AdbdWifiFeature f);

}  // extern "C"
