//! Unsafe native interfaces to the C++ libbinder library. No user servicable
//! parts here.

// Bindings to libbinder generated by bindgen. Ideally we should generate this
// at build time, as is done in the `build.rs` script. However, soong doesn't
// support `build.rs` yet so we pre-generate these bindings and check them into
// the repo. These bindings must be manually re-generated when the libbinder API
// changes.
#[allow(
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    unused,
    improper_ctypes
)]
mod libbinder_bindings {
    use super::service_manager::IServiceManager as android_IServiceManager;
    include!("native/libbinder_bindings.rs");
}

#[macro_use]
mod utils;

mod binder_native;
mod ibinder;
mod parcel;
mod service_manager;
mod state;
mod status;

#[cfg(test)]
mod tests;

pub use binder_native::BinderNative;
pub use ibinder::{IBinder, TransactionCode, TransactionFlags};
pub use libbinder_bindings::{
    android_IPCThreadState as IPCThreadState, android_String16 as String16,
    android_status_t as status_t,
};
pub use parcel::Parcel;
pub use service_manager::{defaultServiceManager, IServiceManager};
pub use state::{flush_commands, start_thread_pool};
pub use status::Status;
pub use utils::{Sp, String8};
