//! Unsafe native interfaces to the C++ libbinder library. No user servicable
//! parts here.

// Bindings to libbinder generated by bindgen. Ideally we should generate this
// at build time, as is done in the `build.rs` script. However, soong doesn't
// support `build.rs` yet so we pre-generate these bindings and check them into
// the repo. These bindings must be manually re-generated when the libbinder API
// changes.
#[allow(
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    unused,
    improper_ctypes
)]
pub(crate) mod libbinder_bindings {
    // We are using a custom opaque declaration for `android_sp` because we want
    // it to be generic over T, but opaque, which bindgen can't do. According to
    // the Rust [nomicon][1], this is how opaque structs should be declared.
    //
    // [1]: https://doc.rust-lang.org/nomicon/ffi.html#representing-opaque-structs
    #[repr(C)]
    pub struct android_sp<T> {
        _opaque: [u8; 0],
        _phantom: std::marker::PhantomData<T>,
    }
    include!("sys/libbinder_bindings.rs");
}

mod status;

#[cfg(test)]
mod tests;

pub use libbinder_bindings::{android_status_t as status_t, binder_size_t};
pub use status::Status;
